/*
========================================================================================
    MODULE : MULTIQC
========================================================================================
    Description : Aggregates all Cell Ranger QC reports (web_summaries, metrics)
                  into a single MultiQC HTML report.
    Outil       : MultiQC 1.21
    Container   : quay.io/biocontainers/multiqc:1.21--pyhdfd78af_0
----------------------------------------------------------------------------------------
    Inputs :
        path(qc_files)       -> List of all QC files to aggregate (collected)
    Outputs :
        path "output_multiqc/multiqc_report_${run_id}.html"
        path "output_multiqc/multiqc_data_${run_id}/"
        path "4_multiqc_versions.yml" → ch_versions
========================================================================================
*/

process MULTIQC {

    tag "4_${run_id}_MultiQC_${params.protocol_prefix}" // Log the run ID for traceability for "MQC" = "MultiQC"
    label 'process_high' // Label for resource allocation

    // Use the shared conda environment available on the cluster
    conda '/labos/UGM/dev/envs/shared/multiqc'

    // Publish MultiQC report and data to specified output directories
    publishDir (
        path    : params.multiqc_output_dir, // Use the specified output directory for MultiQC results
        mode    : 'copy',
        pattern : "output_multiqc/**", // Publish the HTML report and the data directory generated by MultiQC
        saveAs  : { filename -> filename }
    )

    // Publish MultiQC logs to the specified log directory
    publishDir (
        path    : params.multiqc_log_dir, // Use the specified log directory for MultiQC logs
        mode    : 'copy',
        pattern : "logs/*.log"
    )

    input:
        val qc_files   // Collection of all QC files (metrics_summary.csv, web_summary.html, logs)
        val fastqs     // Collection of all FASTQ files
        val run_id      // Run identifier for logging and output naming
        val multiqc_output_dir // Output directory for MultiQC results (val because it's STRING path)
        val multiqc_log_dir // Log directory for MultiQC logs (val because it's STRING path)
        val today_date // Today's date for logging and output naming

    output:
        path "output_multiqc/multiqc_report_${run_id}.html" // Output HTML report named with run_id for traceability
        path "output_multiqc/multiqc_report_${run_id}_data/"
        path "4_multiqc_versions.yml", emit: versions

    script:
        """
        # Exit on error (set -e), undefined variable (set -u), or error in pipeline (set -o pipefail)
        set -euo pipefail

        # Create logs directory if it doesn't exist
        mkdir -p logs output_multiqc

        # Redirect all log (stdout and stderr) to a log file for this process
        exec > >(tee "logs/${today_date}_multiqc_${run_id}.log") 2>&1

        # Load shared logging helpers
        source "${params.logging_script}"

        log_start "Step 4: Performing MultiQC for run_id = ${run_id}..."
        log_log "Logs will be saved to ${multiqc_log_dir}/${today_date}_multiqc_${run_id}.log"

        log_info "
        ╔═══════════════════════════════════════════════════════════════════════════════╗
        ║                         MultiQC Process Script                                ║
        ╠═══════════════════════════════════════════════════════════════════════════════╣
        ║ Logging input parameters:
        ║ - run_id: ${run_id}
        ║ - qc_files: ${qc_files}
        ║ - fastqs: ${fastqs}
        ║ - cpus: ${params.cpu_limit}
        ║ - mem_gb: ${params.memory_limit}
        ║ - multiqc_output_dir: ${multiqc_output_dir}
        ║ - multiqc_log_dir: ${multiqc_log_dir}
        ║ - today_date: ${today_date}
        ╚═══════════════════════════════════════════════════════════════════════════════╝
        "

        # -------------------------------------------------------------------------
        # Initialisation & Verification
        # -------------------------------------------------------------------------
        
        log_verify "Verifying input files and directories..."

        log_info "Received QC files:"
        ls -la ${qc_files.join(' ')}
        ls -la ${fastqs.join(' ')}

        for file in ${qc_files.join(' ')}; do
            if [ ! -f "\$file" ]; then
                log_error "QC file not found: \$file"
            fi
        done

        for dir in ${fastqs.join(' ')}; do
            if [ ! -d "\$dir" ]; then
                log_error "FASTQ directory not found: \$dir"
            fi
        done

        log_ok "Input files and directories verified successfully."

        # -----------------------------------------------------------------------
        # Run MultiQC
        # -----------------------------------------------------------------------
        
        log_start "Running MultiQC for run_id ${run_id}..."
        
        # Create a temporary directory to hold the QC files for MultiQC to scan
        mkdir -p work_qc

        # Copy the parent directories / contents of the qc_files into per-batch subdirs
        # This avoids nested absolute paths and ensures MultiQC sees files under work_qc/<batch>
        for qc_file in ${qc_files.join(' ')}; do
            qc_dir=\$(dirname "\$qc_file")
            base=\$(basename "\$qc_dir")
            mkdir -p "work_qc/\$base"
            # copy contents of the qc dir into work_qc/<base> (preserve files, not leading absolute path)
            cp -r "\$qc_dir"/. "work_qc/\$base/" || cp -r "\$qc_dir" "work_qc/\$base/"
        done

        for fastq_dir in ${fastqs.join(' ')}; do
            base=\$(basename "\$fastq_dir")
            mkdir -p "work_qc/\$base"
            cp -r "\$fastq_dir"/. "work_qc/\$base/" || cp -r "\$fastq_dir" "work_qc/\$base/"
        done

        # Debug: list the gathered files so we can inspect what MultiQC will scan
        echo "--- work_qc contents ---"
        ls -lR work_qc || true

        # Run MultiQC with the specified parameters
        multiqc \\
            ./work_qc/* \\
            --title "MultiQC Report - ${run_id}" \\
            --filename "multiqc_report_${run_id}.html" \\
            --data-dir \\
            --force \\
            --verbose \\
            --dirs \\
            --fullnames \\
            --outdir ./output_multiqc

        # MultiQC v1.14 creates ./output_multiqc/multiqc_data; rename to keep run-specific outputs
        if [ -d "./output_multiqc/multiqc_data" ]; then
            mv "./output_multiqc/multiqc_data" "./output_multiqc/multiqc_data_${run_id}"
        fi


        # -force: Force overwrite of existing output files
        # -verbose: Enable verbose logging for debugging
        # -dirs: Include directory names in the report for clarity
        # -fullnames: Use full file names in the report for traceability
        # --outdir ./output_multiqc: Output results to the multiqc_output directory

        log_ok "MultiQC finished for run_id ${run_id}."

        # -----------------------------------------------------------------------
        # Verify successful execution
        # -----------------------------------------------------------------------
        
        log_verify "Verifying MultiQC output..."
        

        if [ ! -f "./output_multiqc/multiqc_report_${run_id}.html" ]; then
            log_error "MultiQC HTML report was not generated."
        fi

        log_ok "MultiQC output verified."

        log_save "MultiQC report for run_id ${run_id} saved to ${multiqc_output_dir}/multiqc_report_${run_id}.html."

        # -----------------------------------------------------------------------
        # Record tool version
        # -----------------------------------------------------------------------
        
        log_start "Recording tool versions for reproducibility..."

        cat <<-END_VERSIONS > 4_multiqc_versions.yml
        "${task.process}":
            multiqc: \$(multiqc --version 2>&1 | grep -oP 'version \\K[0-9.]+')
        END_VERSIONS

        log_ok "Tool versions recorded successfully in 4_multiqc_versions.yml"

        # -----------------------------------------------------------------------
        # End
        # -----------------------------------------------------------------------

        log_save "MultiQC output for run_id ${run_id} saved to ${multiqc_output_dir}."
        log_log "Versions information will be saved to ${params.run_traceability_log_dir}/${today_date}_versions.yaml"
        log_log "Logs saved to ${multiqc_log_dir}/${today_date}_multiqc_${run_id}.log"

        log_success "MultiQC process completed successfully for run_id = ${run_id} and report available at ${params.multiqc_output_dir}!"
        """
    
    stub:
    """
    mkdir -p logs output_multiqc/multiqc_data_${run_id}
    
    # Create minimal HTML report
    cat > output_multiqc/multiqc_report_${run_id}.html <<EOF
<!DOCTYPE html>
<html>
<head><title>MultiQC Report - ${run_id}</title></head>
<body>
<h1>MultiQC Report (STUB)</h1>
<p>Run ID: ${run_id}</p>
<p>Files processed: stub version</p>
</body>
</html>
EOF
    
    # Create minimal data directory
    touch output_multiqc/multiqc_data_${run_id}/multiqc.log
    
    # Create minimal versions file
    cat > 4_multiqc_versions.yml <<EOF
"MULTIQC":
    "multiqc": "1.21"
    "run_id": "${run_id}"
EOF
    """
}
