/*
========================================================================================
    MODULE : MULTIQC
========================================================================================
    Description : Aggregates all Cell Ranger QC reports (web_summaries, metrics,fastqs)
                  into a single MultiQC HTML report.
    Outil       : MultiQC 1.21
    Container   : quay.io/biocontainers/multiqc:1.21--pyhdfd78af_0
----------------------------------------------------------------------------------------
    Inputs :
        ch_multiqc_input       -> List of all QC files (metrics_summary.csv, web_summary.html, fastqs) for MultiQC aggregation
    Outputs :
        path "multiqc_output_${params.bcl_id}/multiqc_report_${params.bcl_id}.html"
        path "multiqc_output_${params.bcl_id}/multiqc_data_${params.bcl_id}/"
        path "MultiQC_versions_${params.bcl_id}.yml" → ch_versions
========================================================================================
*/

process MULTIQC {

    tag "MQC_${params.bcl_id}_MultiQC_${params.protocol_id}" // Log the run ID for traceability for "MQC" = "MultiQC"
    label 'process_high' // Label for resource allocation

    // Use the shared conda environment available on the cluster
    conda '/labos/UGM/dev/envs/shared/multiqc'

    // Publish MultiQC report and data to specified output directories
    publishDir (
        path    : params.multiqc_output_dir, // Use the specified output directory for MultiQC results
        mode    : 'copy',
        pattern : "multiqc_output_${params.bcl_id}/**", // Publish the HTML report and the data directory generated by MultiQC
        saveAs  : { filename -> filename }
    )

    // Publish MultiQC logs to the specified log directory
    publishDir (
        path    : params.multiqc_log_dir, // Use the specified log directory for MultiQC logs
        mode    : 'copy',
        pattern : "logs/*.log"
    )

    input:
        path ch_multiqc_input

    output:
        path "multiqc_output_${params.bcl_id}/multiqc_report_${params.bcl_id}.html" // Output HTML report named with params.bcl_id for traceability
        path "multiqc_output_${params.bcl_id}/multiqc_data_${params.bcl_id}/"
        path "MultiQC_versions_${params.bcl_id}.yml", emit: ch_versions

    script:
        """
        # Exit on error (set -e), undefined variable (set -u), or error in pipeline (set -o pipefail)
        set -euo pipefail

        # Create logs directory if it doesn't exist
        mkdir -p logs multiqc_output_${params.bcl_id}

        # Redirect all log (stdout and stderr) to a log file for this process
        exec > >(tee "logs/MultiQC_log_${params.bcl_id}.log") 2>&1

        # Load shared logging helpers
        source "${params.logging_script}"

        log_start "Step 4: Performing MultiQC for run_id = ${params.run_id}..."
        
        log_log "Logs will be saved to ${params.multiqc_log_dir}/MultiQC_log_${params.bcl_id}.log"

        log_info "
        ╔═══════════════════════════════════════════════════════════════════════════════╗
        ║                         MultiQC Process Script                                ║
        ╠═══════════════════════════════════════════════════════════════════════════════╣
        ║ Logging input parameters:
        ║ - run_id: ${params.run_id}
        ║ - bcl_id: ${params.bcl_id}
        ║ - cpus: ${params.cpu_limit}
        ║ - mem_gb: ${params.memory_limit}
        ║ - multiqc_output_dir: ${params.multiqc_output_dir}
        ║ - multiqc_log_dir: ${params.multiqc_log_dir}
        ╚═══════════════════════════════════════════════════════════════════════════════╝
        "

        # -------------------------------------------------------------------------
        # Initialisation & Verification
        # -------------------------------------------------------------------------
        
        log_verify "Verifying input files and directories..."

        #log_info "Received QC files:"
        #ls -la ${params.qc_files.join(' ')}
        #ls -la ${params.fastqs.join(' ')}

        #for file in ${params.qc_files.join(' ')}; do
        #    if [ ! -f "\$file" ]; then
        #        log_error "QC file not found: \$file"
        #    fi
        #done

        #for dir in ${params.fastqs.join(' ')}; do
        #    if [ ! -d "\$dir" ]; then
        #        log_error "FASTQ directory not found: \$dir"
        #    fi
        #done

        log_ok "Input files and directories verified successfully."

        # -----------------------------------------------------------------------
        # Run MultiQC
        # -----------------------------------------------------------------------
        
        log_start "Running MultiQC for run_id ${params.run_id}..."
        
        # Create a temporary directory to hold the QC files for MultiQC to scan
        #mkdir -p work_qc

        # Copy the parent directories / contents of the qc_files into per-batch subdirs
        # This avoids nested absolute paths and ensures MultiQC sees files under work_qc/<batch>
        #for qc_file in ${params.qc_files.join(' ')}; do
        #    qc_dir=\$(dirname "\$qc_file")
        #    base=\$(basename "\$qc_dir")
        #    mkdir -p "work_qc/\$base"
        #    # copy contents of the qc dir into work_qc/<base> (preserve files, not leading absolute path)
        #    cp -r "\$qc_dir"/. "work_qc/\$base/" || cp -r "\$qc_dir" "work_qc/\$base/"
        #done

        #for fastq_dir in ${params.fastqs.join(' ')}; do
        #    base=\$(basename "\$fastq_dir")
        #    mkdir -p "work_qc/\$base"
        #    cp -r "\$fastq_dir"/. "work_qc/\$base/" || cp -r "\$fastq_dir" "work_qc/\$base/"
        #done

        # Debug: list the gathered files so we can inspect what MultiQC will scan
        #echo "--- work_qc contents ---"
        #ls -lR work_qc || true

        # Run MultiQC with the specified parameters
        multiqc \\
            ch_multiqc_input \\
            --title "MultiQC Report - ${params.bcl_id}" \\
            --filename "multiqc_report_${params.bcl_id}.html" \\
            --data-dir \\
            --force \\
            --verbose \\
            --dirs \\
            --fullnames \\
            --outdir ./multiqc_output_${params.bcl_id}

        # MultiQC v1.14 creates ./multiqc_output/multiqc_data; rename to keep run-specific outputs
        if [ -d "./multiqc_output_${params.bcl_id}/multiqc_data" ]; then
            mv "./multiqc_output_${params.bcl_id}/multiqc_data" "./multiqc_output_${params.bcl_id}/multiqc_data_${params.bcl_id}"
        fi


        # -force: Force overwrite of existing output files
        # -verbose: Enable verbose logging for debugging
        # -dirs: Include directory names in the report for clarity
        # -fullnames: Use full file names in the report for traceability
        # --outdir ./multiqc_output: Output results to the multiqc_output directory

        log_ok "MultiQC finished for run_id ${params.run_id}."

        # -----------------------------------------------------------------------
        # Verify successful execution
        # -----------------------------------------------------------------------
        
        log_verify "Verifying MultiQC output..."

        if [ ! -f "./multiqc_output_${params.bcl_id}/multiqc_report_${params.bcl_id}.html" ]; then
            log_error "MultiQC HTML report was not generated."
        fi

        log_ok "MultiQC output verified."

        log_save "MultiQC report for run_id ${params.bcl_id} saved to ${params.multiqc_output_dir}/multiqc_report_${params.bcl_id}.html."

        # -----------------------------------------------------------------------
        # Record tool version
        # -----------------------------------------------------------------------
        
        log_start "Recording tool versions for reproducibility..."

        cat <<-END_VERSIONS > MultiQC_versions_${params.bcl_id}.yml
        "${task.process}":
            multiqc: \$(multiqc --version 2>&1 | grep -oP 'version \\K[0-9.]+')
        END_VERSIONS

        log_ok "Tool versions recorded successfully in MultiQC_versions_${params.bcl_id}.yml"

        # -----------------------------------------------------------------------
        # End
        # -----------------------------------------------------------------------

        log_save "MultiQC output for run_id ${params.run_id} saved to ${params.multiqc_output_dir}."
        log_log "Versions information will be saved to ${params.run_traceability_log_dir}/MultiQC_versions_${params.bcl_id}.yml"
        log_log "Logs saved to ${params.multiqc_log_dir}/MultiQC_log_${params.bcl_id}.log"

        log_success "MultiQC process completed successfully for run_id = ${params.run_id} and report available at ${params.multiqc_output_dir}!"
        """
    
    stub:
    """
    mkdir -p logs multiqc_output_${params.bcl_id}/multiqc_data_${params.bcl_id}
    
    # Create minimal HTML report
    cat > multiqc_output_${params.bcl_id}/multiqc_report_${params.bcl_id}.html <<EOF
<!DOCTYPE html>
<html>
<head><title>MultiQC Report - ${params.bcl_id}</title></head>
<body>
<h1>MultiQC Report (STUB)</h1>
<p>Run ID: ${params.run_id}</p>
<p>Files processed: stub version</p>
</body>
</html>
EOF
    
    # Create minimal data directory
    touch multiqc_output_${params.bcl_id}/multiqc_data_${params.bcl_id}/multiqc.log
    
    # Create minimal versions file
    cat > MultiQC_versions_${params.bcl_id}.yml <<EOF
"MULTIQC":
    "multiqc": "1.21"
    "run_id": "${params.bcl_id}"
EOF
    """
}
