/*
========================================================================================
    MODULE : MULTIQC
========================================================================================
    Description : Aggregates all Cell Ranger QC reports (web_summaries, metrics)
                  into a single MultiQC HTML report.
    Outil       : MultiQC 1.21
    Container   : quay.io/biocontainers/multiqc:1.21--pyhdfd78af_0
----------------------------------------------------------------------------------------
    Inputs :
        path(qc_files)       -> List of all QC files to aggregate (collected)
    Outputs :
        path "output_multiqc/multiqc_report_${run_id}.html"
        path "output_multiqc/multiqc_data_${run_id}/"
        path "versions.yml"          → ch_versions
========================================================================================
*/

process MULTIQC {

    tag "multiqc | global QC aggregation | run: ${run_id}" // Log the run ID for traceability
    label 'process_low' // Label for resource allocation

    // Use container for reproducibility
    container 'quay.io/biocontainers/multiqc:1.21--pyhdfd78af_0'

    // Publish MultiQC report and data to specified output directories
    publishDir (
        path    : multiqc_output_dir, // Use the specified output directory for MultiQC results
        mode    : 'copy',
        pattern : "output_multiqc/**", // Publish the HTML report and the data directory generated by MultiQC
        saveAs  : { filename -> filename }
    )

    // Publish MultiQC logs to the specified log directory
    publishDir (
        path    : multiqc_log_dir, // Use the specified log directory for MultiQC logs
        mode    : 'copy',
        pattern : "multiqc_${run_id}.log"
    )

    input:
        path qc_files   // Collection of all QC files (metrics_summary.csv, web_summary.html, logs)
        val run_id      // Run identifier for logging and output naming
        val multiqc_output_dir // Output directory for MultiQC results (val because it's STRING path)
        val multiqc_log_dir // Log directory for MultiQC logs (val because it's STRING path)

    output:
        path "output_multiqc/multiqc_report_${run_id}.html" // Output HTML report named with run_id for traceability
        path "output_multiqc/multiqc_data_${run_id}/"
        path "versions.yml", emit: versions

    script:
        """
        exec > >(tee "multiqc_${run_id}.log") 2>&1

        # -----------------------------------------------------------------------
        # Input checks
        # -----------------------------------------------------------------------
        echo "[$(date '+%Y-%m-%d %H:%M:%S')] Starting MultiQC"
        echo "[$(date '+%Y-%m-%d %H:%M:%S')] Received QC files:"
        ls -la .

        # Create dir multiqc_output if it doesn't exist
        mkdir -p output_multiqc

        # -----------------------------------------------------------------------
        # Run MultiQC
        # -----------------------------------------------------------------------
        multiqc \\
            . \\
            --title "MultiQC Report - ${run_id}" \\
            --filename "multiqc_report_${run_id}.html" \\
            --data-dir-name "multiqc_data_${run_id}" \\
            --force \\
            --verbose \\
            --dirs \\
            --fullnames \\
            --outdir ./output_multiqc

        # -force: Force overwrite of existing output files
        # -verbose: Enable verbose logging for debugging
        # -dirs: Include directory names in the report for clarity
        # -fullnames: Use full file names in the report for traceability
        # --outdir ./output_multiqc: Output results to the multiqc_output directory




        EXIT_CODE=\$?

        # -----------------------------------------------------------------------
        # Verify successful execution
        # -----------------------------------------------------------------------
        if [ \$EXIT_CODE -ne 0 ]; then
            echo "[ERROR] MultiQC failed with exit code \$EXIT_CODE." >&2
            exit \$EXIT_CODE
        fi

        if [ ! -f "./output_multiqc/multiqc_report_${run_id}.html" ]; then
            echo "[ERROR] MultiQC HTML report was not generated." >&2
            exit 1
        fi

        echo "[$(date '+%Y-%m-%d %H:%M:%S')] MultiQC completed. Report: ./output_multiqc/multiqc_report_${run_id}.html"

        # -----------------------------------------------------------------------
        # Record tool version
        # -----------------------------------------------------------------------
        cat <<-END_VERSIONS > versions.yml
        "${task.process}":
            multiqc: \$(multiqc --version 2>&1 | grep -oP 'version \\K[0-9.]+')
        END_VERSIONS
        """
}
