/*
========================================================================================
    MODULE : MULTIQC
========================================================================================
    Description : Aggregates all Cell Ranger QC reports (web_summaries, metrics)
                  into a single MultiQC HTML report.
    Outil       : MultiQC 1.21
    Container   : quay.io/biocontainers/multiqc:1.21--pyhdfd78af_0
----------------------------------------------------------------------------------------
    Inputs :
        path(qc_files)       -> List of all QC files to aggregate (collected)
    Outputs :
        path "output_multiqc/multiqc_report_${run_id}.html"
        path "output_multiqc/multiqc_data_${run_id}/"
        path "versions.yml"          → ch_versions
========================================================================================
*/

process MULTIQC {

    tag "${task.process.toLowerCase()}_${run_id}" // Log the run ID for traceability
    label 'process_high' // Label for resource allocation

    // Use container for reproducibility
    container 'quay.io/biocontainers/multiqc:1.21--pyhdfd78af_0'

    // Publish MultiQC report and data to specified output directories
    publishDir (
        path    : multiqc_output_dir, // Use the specified output directory for MultiQC results
        mode    : 'copy',
        pattern : "output_multiqc/**", // Publish the HTML report and the data directory generated by MultiQC
        saveAs  : { filename -> filename }
    )

    // Publish MultiQC logs to the specified log directory
    publishDir (
        path    : multiqc_log_dir, // Use the specified log directory for MultiQC logs
        mode    : 'copy',
        pattern : "logs/${today_date}_multiqc_${run_id}.log"
    )

    input:
        path qc_files   // Collection of all QC files (metrics_summary.csv, web_summary.html, logs)
        val run_id      // Run identifier for logging and output naming
        val multiqc_output_dir // Output directory for MultiQC results (val because it's STRING path)
        val multiqc_log_dir // Log directory for MultiQC logs (val because it's STRING path)
        val today_date // Today's date for logging and output naming

    output:
        path "output_multiqc/multiqc_report_${run_id}.html" // Output HTML report named with run_id for traceability
        path "output_multiqc/multiqc_data_${run_id}/"
        path "versions.yml", emit: versions

    script:
        """
        # Exit on error (set -e), undefined variable (set -u), or error in pipeline (set -o pipefail)
        set -euo pipefail

        # Create logs directory if it doesn't exist
        mkdir -p logs output_multiqc

        # Redirect all log (stdout and stderr) to a log file for this process
        exec > >(tee "logs/${today_date}_multiqc_${run_id}.log") 2>&1

        # Load shared logging helpers
        source "${params.logging_script}"

        log_info "
        ╔═══════════════════════════════════════════════════════════════════════════════╗
        ║                         MultiQC Process Script                                ║
        ╠═══════════════════════════════════════════════════════════════════════════════╣
        ║ Logging input parameters:                                                     ║
        ║ - run_id: ${run_id}                                                           ║
        ║ - qc_files: ${qc_files}                                                       ║
        ║ - cpus: ${task.cpus}                                                          ║
        ║ - mem_gb: ${task.memory.toGiga()}                                             ║
        ║ - multiqc_output_dir: ${multiqc_output_dir}                                   ║
        ║ - multiqc_log_dir: ${multiqc_log_dir}                                         ║
        ║ - today_date: ${today_date}                                                   ║
        ╚═══════════════════════════════════════════════════════════════════════════════╝
        "

        log_start "Starting MultiQC for run_id ${run_id}..."

        # -------------------------------------------------------------------------
        # Initialisation & Verification
        # -------------------------------------------------------------------------
        
        log_verify "Verifying input files and directories..."

        log_info "Received QC files:"
        ls -la ${qc_files}

        if [ -z "$(ls -A ${qc_files})" ]; then
            log_error "No QC files found in the input directory: ${qc_files}"
        fi

        log_ok "Input files and directories verified successfully."

        # -----------------------------------------------------------------------
        # Run MultiQC
        # -----------------------------------------------------------------------
        
        log_start "Running MultiQC for run_id ${run_id}..."
        
        multiqc \\
            . \\
            --title "MultiQC Report - ${run_id}" \\
            --filename "multiqc_report_${run_id}.html" \\
            --data-dir-name "multiqc_data_${run_id}" \\
            --force \\
            --verbose \\
            --dirs \\
            --fullnames \\
            --outdir ./output_multiqc

        # -force: Force overwrite of existing output files
        # -verbose: Enable verbose logging for debugging
        # -dirs: Include directory names in the report for clarity
        # -fullnames: Use full file names in the report for traceability
        # --outdir ./output_multiqc: Output results to the multiqc_output directory

        EXIT_CODE=\$?

        log_ok "MultiQC finished for run_id ${run_id} with exit code \$EXIT_CODE."

        # -----------------------------------------------------------------------
        # Verify successful execution
        # -----------------------------------------------------------------------
        
        log_verify "Verifying MultiQC output..."
        
        if [ \$EXIT_CODE -ne 0 ]; then
            log_error "MultiQC failed with exit code \$EXIT_CODE."
        fi

        if [ ! -f "./output_multiqc/multiqc_report_${run_id}.html" ]; then
            log_error "MultiQC HTML report was not generated."
        fi

        log_ok "MultiQC output verified."

        log_save "MultiQC report for run_id ${run_id} saved to ${multiqc_output_dir}/multiqc_report_${run_id}.html."

        # -----------------------------------------------------------------------
        # Record tool version
        # -----------------------------------------------------------------------
        
        log_start "Recording tool versions for reproducibility..."

        cat <<-END_VERSIONS > versions.yml
        "${task.process}":
            multiqc: \$(multiqc --version 2>&1 | grep -oP 'version \\K[0-9.]+')
        END_VERSIONS

        log_ok "Tool versions recorded successfully in versions.yml"

        # -----------------------------------------------------------------------
        # End
        # -----------------------------------------------------------------------

        log_save "MultiQC output for run_id ${run_id} saved to ${multiqc_output_dir}."
        log_log "Versions information will be saved to ${params.log_dir}/versions.yml"
        log_log "Logs saved to ${multiqc_log_dir}/${today_date}_multiqc_${run_id}.log"

        log_success "MultiQC process completed successfully for run_id = ${run_id} !"
        """
}
